name: nightly

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker_build.yml
    with:
      nightly: true
    permissions:
      packages: write
      contents: read
    secrets: inherit

  test:
    needs: [build]
    uses: ./.github/workflows/rspamd_test.yml
    with:
      image: ghcr.io/${{ github.repository }}:nightly
      tag: "${{ needs.build.outputs.tag }}"
